# Generated by Django 6.0.5 on 2026-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=50)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
