# Generated by Django 6.0.5 on 2026-07-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
